check.k8s.env.actions: false
ingress.controller: nginx
id: kubernetes
jaegerAction: addon-jaeger
monitoringAction: addon-monitoring
helm.version: v3.7.2
cni.plugins.version: 1.1.1
k9s.version: 0.25.18
crictl.version: v1.23.0
stern.version: 1.11.0
containerd.version: 1.3.9
ingress.nginx.version: 1.1.2
kubernetes.dashboard.version: 2.5.1
metallb.version: 0.12.1