check.k8s.env.actions: false
ingress.controller: nginx
id: kubernetes
jaegerAction: addon-jaeger
monitoringAction: addon-monitoring
cni.plugins.version: 1.1.1
k9s.version: 0.25.18
stern.version: 1.11.0
crictl.version: v1.23.0
helm.version: v3.7.2
containerd.version: 1.3.7
ingress.nginx.version: 1.3.0
metallb.version: 0.13.4
kubernetes.dashboard.version: 2.6.1