check.k8s.env.actions: false
ingress.controller: nginx
id: kubernetes
jaegerAction: addon-jaeger
monitoringAction: addon-monitoring
helm.version: v3.6.3
cni.plugins.version: 1.0.1
k9s.version: 0.25.6
crictl.version: v1.22.0
stern.version: 1.11.0
containerd.version: 1.3.9
ingress.nginx.version: 1.1.0
kubernetes.dashboard.version: 2.4.0
metallb.version: 0.11.0